// Code generated by yamlvalidator-gen; DO NOT EDIT.

package model

import (
	"fmt"
	"github.com/Yakwilik/go-yamlvalidator"
	"gopkg.in/yaml.v3"
	"reflect"
	"sort"
)

var _ = fmt.Sprintf
var _ = sort.Strings

func (value Config) YAMLValidatorGeneratedType() reflect.Type { return reflect.TypeFor[Config]() }
func (value Config) YAMLValidatorEncode() (*yaml.Node, error) {
	return yamlvalidatorEncode_28ba702d0(value)
}
func (value *Config) YAMLValidatorDecode(node *yaml.Node) error {
	return value.YAMLValidatorDecodeWithContext(node, yamlvalidator.NewGeneratedDecodeContext(yamlvalidator.Limits{}, false))
}
func (value *Config) YAMLValidatorDecodeWithContext(node *yaml.Node, ctx *yamlvalidator.GeneratedDecodeContext) error {
	return yamlvalidatorDecode_28ba702d0(node, value, ctx)
}
func (value Config) MarshalYAML() (any, error) { return yamlvalidator.MarshalGenerated(value) }
func (value *Config) UnmarshalYAML(node *yaml.Node) error {
	return yamlvalidator.UnmarshalGenerated(node, value)
}

func (value Config) YAMLValidatorTypePlan() yamlvalidator.SourceTypePlan {
	return yamlvalidator.SourceTypePlan{Type: reflect.TypeFor[Config](), Fields: []reflect.StructField{{Name: "Name", Type: reflect.TypeFor[string](), Tag: reflect.StructTag("yaml:\"name\" yamlvalidate:\"required,nonempty\""), Anonymous: false, PkgPath: ""}, {Name: "Items", Type: reflect.TypeFor[[]Item](), Tag: reflect.StructTag("yaml:\"items,omitempty\" yamlvalidate:\"items={nonempty}\""), Anonymous: false, PkgPath: ""}, {Name: "Extra", Type: reflect.TypeFor[map[string]int](), Tag: reflect.StructTag("yaml:\"extra,omitempty\""), Anonymous: false, PkgPath: ""}}}
}

func (value Containers) YAMLValidatorGeneratedType() reflect.Type {
	return reflect.TypeFor[Containers]()
}
func (value Containers) YAMLValidatorEncode() (*yaml.Node, error) {
	return yamlvalidatorEncode_28ba702d6(value)
}
func (value *Containers) YAMLValidatorDecode(node *yaml.Node) error {
	return value.YAMLValidatorDecodeWithContext(node, yamlvalidator.NewGeneratedDecodeContext(yamlvalidator.Limits{}, false))
}
func (value *Containers) YAMLValidatorDecodeWithContext(node *yaml.Node, ctx *yamlvalidator.GeneratedDecodeContext) error {
	return yamlvalidatorDecode_28ba702d6(node, value, ctx)
}
func (value Containers) MarshalYAML() (any, error) { return yamlvalidator.MarshalGenerated(value) }
func (value *Containers) UnmarshalYAML(node *yaml.Node) error {
	return yamlvalidator.UnmarshalGenerated(node, value)
}

func (value Containers) YAMLValidatorTypePlan() yamlvalidator.SourceTypePlan {
	return yamlvalidator.SourceTypePlan{Type: reflect.TypeFor[Containers](), Fields: []reflect.StructField{{Name: "Items", Type: reflect.TypeFor[[]string](), Tag: reflect.StructTag("yaml:\"items\""), Anonymous: false, PkgPath: ""}, {Name: "Values", Type: reflect.TypeFor[map[string]string](), Tag: reflect.StructTag("yaml:\"values\""), Anonymous: false, PkgPath: ""}}}
}

func (value Dynamic) YAMLValidatorGeneratedType() reflect.Type { return reflect.TypeFor[Dynamic]() }
func (value Dynamic) YAMLValidatorEncode() (*yaml.Node, error) {
	return yamlvalidatorEncode_28ba702d9(value)
}
func (value *Dynamic) YAMLValidatorDecode(node *yaml.Node) error {
	return value.YAMLValidatorDecodeWithContext(node, yamlvalidator.NewGeneratedDecodeContext(yamlvalidator.Limits{}, false))
}
func (value *Dynamic) YAMLValidatorDecodeWithContext(node *yaml.Node, ctx *yamlvalidator.GeneratedDecodeContext) error {
	return yamlvalidatorDecode_28ba702d9(node, value, ctx)
}
func (value Dynamic) MarshalYAML() (any, error) { return yamlvalidator.MarshalGenerated(value) }
func (value *Dynamic) UnmarshalYAML(node *yaml.Node) error {
	return yamlvalidator.UnmarshalGenerated(node, value)
}

func (value Dynamic) YAMLValidatorTypePlan() yamlvalidator.SourceTypePlan {
	return yamlvalidator.SourceTypePlan{Type: reflect.TypeFor[Dynamic](), Fields: []reflect.StructField{{Name: "Value", Type: reflect.TypeFor[any](), Tag: reflect.StructTag("yaml:\"value\" yamlvalidate:\"type=any\""), Anonymous: false, PkgPath: ""}}}
}

func (value Item) YAMLValidatorGeneratedType() reflect.Type { return reflect.TypeFor[Item]() }
func (value Item) YAMLValidatorEncode() (*yaml.Node, error) {
	return yamlvalidatorEncode_28ba702d3(value)
}
func (value *Item) YAMLValidatorDecode(node *yaml.Node) error {
	return value.YAMLValidatorDecodeWithContext(node, yamlvalidator.NewGeneratedDecodeContext(yamlvalidator.Limits{}, false))
}
func (value *Item) YAMLValidatorDecodeWithContext(node *yaml.Node, ctx *yamlvalidator.GeneratedDecodeContext) error {
	return yamlvalidatorDecode_28ba702d3(node, value, ctx)
}
func (value Item) MarshalYAML() (any, error) { return yamlvalidator.MarshalGenerated(value) }
func (value *Item) UnmarshalYAML(node *yaml.Node) error {
	return yamlvalidator.UnmarshalGenerated(node, value)
}

// yamlvalidator source fingerprint: eb31e75c16de18528ccf57d7
func yamlvalidatorEncode_28ba702d0(value Config) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	var child *yaml.Node
	var err error
	child, err = yamlvalidatorEncode_28ba702d1(value.Name)
	if err != nil {
		return nil, fmt.Errorf("field Name: %w", err)
	}
	node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "name"}, child)
	if !yamlvalidator.GeneratedIsEmpty(value.Items) {
		child, err = yamlvalidatorEncode_28ba702d2(value.Items)
		if err != nil {
			return nil, fmt.Errorf("field Items: %w", err)
		}
		node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "items"}, child)
	}
	if !yamlvalidator.GeneratedIsEmpty(value.Extra) {
		child, err = yamlvalidatorEncode_28ba702d4(value.Extra)
		if err != nil {
			return nil, fmt.Errorf("field Extra: %w", err)
		}
		node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "extra"}, child)
	}
	return node, nil
}
func yamlvalidatorDecode_28ba702d0(node *yaml.Node, dst *Config, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	pairs, err := ctx.MappingPairs(node)
	if err != nil {
		return err
	}
	for _, pair := range pairs {
		switch pair.Key {
		case "name":
			if err := yamlvalidatorDecode_28ba702d1(pair.Value, &dst.Name, ctx); err != nil {
				return fmt.Errorf("field Name: %w", err)
			}
		case "items":
			if err := yamlvalidatorDecode_28ba702d2(pair.Value, &dst.Items, ctx); err != nil {
				return fmt.Errorf("field Items: %w", err)
			}
		case "extra":
			if err := yamlvalidatorDecode_28ba702d4(pair.Value, &dst.Extra, ctx); err != nil {
				return fmt.Errorf("field Extra: %w", err)
			}
		}
	}
	return nil
}
func yamlvalidatorEncode_28ba702d1(value string) (*yaml.Node, error) {
	return yamlvalidator.GeneratedScalarEncode(value)
}
func yamlvalidatorDecode_28ba702d1(node *yaml.Node, dst *string, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	return yamlvalidator.GeneratedScalarDecode(node, dst)
}
func yamlvalidatorEncode_28ba702d2(value []Item) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	for _, item := range value {
		child, err := yamlvalidatorEncode_28ba702d3(item)
		if err != nil {
			return nil, err
		}
		node.Content = append(node.Content, child)
	}
	return node, nil
}
func yamlvalidatorDecode_28ba702d2(node *yaml.Node, dst *[]Item, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	var err error
	node, err = ctx.Resolve(node)
	if err != nil {
		return err
	}
	if node.Tag == "!!null" {
		*dst = nil
		return nil
	}
	if node.Kind != yaml.SequenceNode {
		return fmt.Errorf("expected YAML sequence")
	}
	result := make([]Item, len(node.Content))
	for i, item := range node.Content {
		if err := yamlvalidatorDecode_28ba702d3(item, &result[i], ctx); err != nil {
			return fmt.Errorf("item %d: %w", i, err)
		}
	}
	*dst = result
	return nil
}
func yamlvalidatorEncode_28ba702d3(value Item) (*yaml.Node, error) {
	return yamlvalidator.GeneratedScalarEncode(string(value))
}
func yamlvalidatorDecode_28ba702d3(node *yaml.Node, dst *Item, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	scalar := string(*dst)
	if err := yamlvalidator.GeneratedScalarDecode(node, &scalar); err != nil {
		return err
	}
	*dst = Item(scalar)
	return nil
}
func yamlvalidatorEncode_28ba702d4(value map[string]int) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	keys := make([]string, 0, len(value))
	for key := range value {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	for _, key := range keys {
		child, err := yamlvalidatorEncode_28ba702d5(value[key])
		if err != nil {
			return nil, err
		}
		node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: string(key)}, child)
	}
	return node, nil
}
func yamlvalidatorDecode_28ba702d4(node *yaml.Node, dst *map[string]int, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	var err error
	node, err = ctx.Resolve(node)
	if err != nil {
		return err
	}
	if node.Tag == "!!null" {
		*dst = nil
		return nil
	}
	pairs, err := ctx.MappingPairs(node)
	if err != nil {
		return err
	}
	if *dst == nil {
		*dst = make(map[string]int, len(pairs))
	}
	for _, pair := range pairs {
		var item int
		if err := yamlvalidatorDecode_28ba702d5(pair.Value, &item, ctx); err != nil {
			return fmt.Errorf("key %q: %w", pair.Key, err)
		}
		(*dst)[string(pair.Key)] = item
	}
	return nil
}
func yamlvalidatorEncode_28ba702d5(value int) (*yaml.Node, error) {
	return yamlvalidator.GeneratedScalarEncode(value)
}
func yamlvalidatorDecode_28ba702d5(node *yaml.Node, dst *int, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	return yamlvalidator.GeneratedScalarDecode(node, dst)
}

// yamlvalidator source fingerprint: 56f7e9d20392a142fe7f79ce
func yamlvalidatorEncode_28ba702d6(value Containers) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	var child *yaml.Node
	var err error
	child, err = yamlvalidatorEncode_28ba702d7(value.Items)
	if err != nil {
		return nil, fmt.Errorf("field Items: %w", err)
	}
	node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "items"}, child)
	child, err = yamlvalidatorEncode_28ba702d8(value.Values)
	if err != nil {
		return nil, fmt.Errorf("field Values: %w", err)
	}
	node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "values"}, child)
	return node, nil
}
func yamlvalidatorDecode_28ba702d6(node *yaml.Node, dst *Containers, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	pairs, err := ctx.MappingPairs(node)
	if err != nil {
		return err
	}
	for _, pair := range pairs {
		switch pair.Key {
		case "items":
			if err := yamlvalidatorDecode_28ba702d7(pair.Value, &dst.Items, ctx); err != nil {
				return fmt.Errorf("field Items: %w", err)
			}
		case "values":
			if err := yamlvalidatorDecode_28ba702d8(pair.Value, &dst.Values, ctx); err != nil {
				return fmt.Errorf("field Values: %w", err)
			}
		}
	}
	return nil
}
func yamlvalidatorEncode_28ba702d7(value []string) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	for _, item := range value {
		child, err := yamlvalidatorEncode_28ba702d1(item)
		if err != nil {
			return nil, err
		}
		node.Content = append(node.Content, child)
	}
	return node, nil
}
func yamlvalidatorDecode_28ba702d7(node *yaml.Node, dst *[]string, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	var err error
	node, err = ctx.Resolve(node)
	if err != nil {
		return err
	}
	if node.Tag == "!!null" {
		*dst = nil
		return nil
	}
	if node.Kind != yaml.SequenceNode {
		return fmt.Errorf("expected YAML sequence")
	}
	result := make([]string, len(node.Content))
	for i, item := range node.Content {
		if err := yamlvalidatorDecode_28ba702d1(item, &result[i], ctx); err != nil {
			return fmt.Errorf("item %d: %w", i, err)
		}
	}
	*dst = result
	return nil
}
func yamlvalidatorEncode_28ba702d8(value map[string]string) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	keys := make([]string, 0, len(value))
	for key := range value {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	for _, key := range keys {
		child, err := yamlvalidatorEncode_28ba702d1(value[key])
		if err != nil {
			return nil, err
		}
		node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: string(key)}, child)
	}
	return node, nil
}
func yamlvalidatorDecode_28ba702d8(node *yaml.Node, dst *map[string]string, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	var err error
	node, err = ctx.Resolve(node)
	if err != nil {
		return err
	}
	if node.Tag == "!!null" {
		*dst = nil
		return nil
	}
	pairs, err := ctx.MappingPairs(node)
	if err != nil {
		return err
	}
	if *dst == nil {
		*dst = make(map[string]string, len(pairs))
	}
	for _, pair := range pairs {
		var item string
		if err := yamlvalidatorDecode_28ba702d1(pair.Value, &item, ctx); err != nil {
			return fmt.Errorf("key %q: %w", pair.Key, err)
		}
		(*dst)[string(pair.Key)] = item
	}
	return nil
}

// yamlvalidator source fingerprint: 7108560b1c5344172c6a47c5
func yamlvalidatorEncode_28ba702d9(value Dynamic) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	var child *yaml.Node
	var err error
	child, err = yamlvalidatorEncode_28ba702d10(value.Value)
	if err != nil {
		return nil, fmt.Errorf("field Value: %w", err)
	}
	node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "value"}, child)
	return node, nil
}
func yamlvalidatorDecode_28ba702d9(node *yaml.Node, dst *Dynamic, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	pairs, err := ctx.MappingPairs(node)
	if err != nil {
		return err
	}
	for _, pair := range pairs {
		switch pair.Key {
		case "value":
			if err := yamlvalidatorDecode_28ba702d10(pair.Value, &dst.Value, ctx); err != nil {
				return fmt.Errorf("field Value: %w", err)
			}
		}
	}
	return nil
}
func yamlvalidatorEncode_28ba702d10(value any) (*yaml.Node, error) {
	return yamlvalidator.GeneratedFallbackEncode(value)
}
func yamlvalidatorDecode_28ba702d10(node *yaml.Node, dst *any, ctx *yamlvalidator.GeneratedDecodeContext) error {
	if err := ctx.Enter(); err != nil {
		return err
	}
	defer ctx.Leave()
	return yamlvalidator.GeneratedFallbackDecodeWithContext(node, dst, ctx)
}
