// Command yamlvalidator-gen generates typed YAML node codecs for selected Go types.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"hash/fnv"
	"math/big"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/Yakwilik/go-yamlvalidator/internal/taglang"
	"golang.org/x/tools/go/packages"
)

const marker = "// Code generated by yamlvalidator-gen; DO NOT EDIT."

func main() {
	typesFlag := flag.String("type", "", "comma-separated type names")
	all := flag.Bool("all", false, "generate all eligible named struct types in the package")
	output := flag.String("output", "zz_yamlvalidator_generated.go", "output Go file")
	check := flag.Bool("check", false, "report stale output without writing")
	flag.Parse()
	if err := run(*typesFlag, *all, *output, *check); err != nil {
		fmt.Fprintln(os.Stderr, "yamlvalidator-gen:", err)
		os.Exit(1)
	}
}

func run(namesText string, all bool, output string, check bool) error {
	if namesText == "" && !all {
		return fmt.Errorf("-type or -all is required")
	}
	if len(flag.Args()) != 0 {
		return fmt.Errorf("unexpected arguments: %s", strings.Join(flag.Args(), " "))
	}
	if filepath.Ext(output) != ".go" {
		return fmt.Errorf("output must be a .go file")
	}
	path, err := filepath.Abs(output)
	if err != nil {
		return err
	}
	old, readErr := os.ReadFile(path)
	if readErr != nil && !os.IsNotExist(readErr) {
		return readErr
	}
	if readErr == nil && !bytes.HasPrefix(old, []byte(marker)) {
		return fmt.Errorf("refusing to overwrite user-owned output %s", output)
	}
	names, err := selectRootNames(namesText, all, path)
	if err != nil {
		return err
	}
	seen := make(map[string]bool, len(names))
	for _, name := range names {
		seen[name] = true
	}
	config := &packages.Config{Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo, Dir: ".", Tests: false}
	if readErr == nil {
		file, err := parser.ParseFile(token.NewFileSet(), path, old, parser.PackageClauseOnly)
		if err != nil {
			return fmt.Errorf("existing generated output: %w", err)
		}
		stubs, err := generatedStubs(old, file.Name.Name, names)
		if err != nil {
			return err
		}
		config.Overlay = map[string][]byte{path: []byte(stubs)}
	}
	loaded, err := packages.Load(config, ".")
	if err != nil {
		return err
	}
	if len(loaded) != 1 {
		return fmt.Errorf("expected one package, found %d", len(loaded))
	}
	pkg := loaded[0]
	if len(pkg.Errors) > 0 {
		return fmt.Errorf("load package: %s", pkg.Errors[0])
	}
	if err := rejectConditionalTypes(pkg, names); err != nil {
		return err
	}
	g := &generator{pkg: pkg.Types, ids: map[string]int{}, imports: map[string]string{}, rootsByName: seen, schemaFields: map[int][]schemaField{}}
	for _, name := range names {
		obj := pkg.Types.Scope().Lookup(name)
		typ, ok := obj.(*types.TypeName)
		if !ok || typ.IsAlias() {
			return fmt.Errorf("type %q is not a named type in package %s", name, pkg.Name)
		}
		named, ok := types.Unalias(typ.Type()).(*types.Named)
		if !ok {
			return fmt.Errorf("type %s: aliases are unsupported", name)
		}
		if named.TypeParams() != nil && named.TypeParams().Len() > 0 {
			return fmt.Errorf("type %s: generic type parameters are unsupported", name)
		}
		for _, method := range []string{"MarshalYAML", "UnmarshalYAML", "YAMLValidatorEncode", "YAMLValidatorDecode", "YAMLValidatorDecodeWithContext", "YAMLValidatorGeneratedType", "YAMLValidatorSchema", "YAMLValidatorCheckCycles"} {
			for i := 0; i < named.NumMethods(); i++ {
				if named.Method(i).Name() == method && filepath.Clean(pkg.Fset.Position(named.Method(i).Pos()).Filename) != filepath.Clean(path) {
					return fmt.Errorf("type %s: method %s already exists", name, method)
				}
			}
		}
		id, err := g.ensure(named)
		if err != nil {
			return fmt.Errorf("type %s: %w", name, err)
		}
		g.roots = append(g.roots, root{name: name, id: id})
	}
	var source strings.Builder
	source.WriteString(marker + "\n\npackage " + pkg.Name + "\n\nimport (\n\"fmt\"\n\"reflect\"\n\"sort\"\n\"strconv\"\n\"github.com/Yakwilik/go-yamlvalidator\"\n\"gopkg.in/yaml.v3\"\n")
	paths := make([]string, 0, len(g.imports))
	for path := range g.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		fmt.Fprintf(&source, "%s %q\n", g.imports[path], path)
	}
	source.WriteString(")\n\nvar _ = fmt.Sprintf\nvar _ = sort.Strings\nvar _ = strconv.IntSize\n\n")
	for _, r := range g.roots {
		fmt.Fprintf(&source, "func (value %s) YAMLValidatorGeneratedType() reflect.Type { return reflect.TypeFor[%s]() }\n", r.name, r.name)
		fmt.Fprintf(&source, "func (value %s) YAMLValidatorCheckCycles(limits yamlvalidator.Limits) error { return yamlvalidatorCycle%d(value,yamlvalidator.NewGeneratedCycleContext(limits),0) }\n", r.name, r.id)
		fmt.Fprintf(&source, "func (value %s) YAMLValidatorSchema(registry *yamlvalidator.Registry, encode bool) (*yamlvalidator.FieldSchema,error) { return yamlvalidatorGeneratedSchema%d(registry,encode) }\n", r.name, r.id)
		fmt.Fprintf(&source, "func (value %s) YAMLValidatorEncode() (*yaml.Node,error) { return yamlvalidatorEncode%d(value) }\n", r.name, r.id)
		fmt.Fprintf(&source, "func (value *%s) YAMLValidatorDecode(node *yaml.Node) error { return value.YAMLValidatorDecodeWithContext(node,yamlvalidator.NewGeneratedDecodeContext(yamlvalidator.Limits{},false)) }\n", r.name)
		fmt.Fprintf(&source, "func (value *%s) YAMLValidatorDecodeWithContext(node *yaml.Node,ctx *yamlvalidator.GeneratedDecodeContext) error { return yamlvalidatorDecode%d(node,value,ctx) }\n", r.name, r.id)
		fmt.Fprintf(&source, "func (value %s) MarshalYAML() (any,error) { return yamlvalidator.MarshalGenerated(value) }\n", r.name)
		fmt.Fprintf(&source, "func (value *%s) UnmarshalYAML(node *yaml.Node) error { return yamlvalidator.UnmarshalGenerated(node,value) }\n\n", r.name)
	}
	schemaSource, err := g.schemaGraphSource()
	if err != nil {
		return err
	}
	source.WriteString(schemaSource)
	for _, body := range g.bodies {
		source.WriteString(body)
	}
	source.WriteString(g.emptyCycleSource())
	h := fnv.New32a()
	_, _ = h.Write([]byte(filepath.Base(output)))
	prefix := fmt.Sprintf("_%08x", h.Sum32())
	raw := strings.ReplaceAll(source.String(), "yamlvalidatorEncode", "yamlvalidatorEncode"+prefix)
	raw = strings.ReplaceAll(raw, "yamlvalidatorDecode", "yamlvalidatorDecode"+prefix)
	raw = strings.ReplaceAll(raw, "yamlvalidatorEmpty", "yamlvalidatorEmpty"+prefix)
	raw = strings.ReplaceAll(raw, "yamlvalidatorCycle", "yamlvalidatorCycle"+prefix)
	raw = strings.ReplaceAll(raw, "yamlvalidatorGeneratedSchemaGraph", "yamlvalidatorGeneratedSchemaGraph"+prefix)
	raw = strings.ReplaceAll(raw, "yamlvalidatorGeneratedTypes", "yamlvalidatorGeneratedTypes"+prefix)
	raw = strings.ReplaceAll(raw, "yamlvalidatorGeneratedSchema", "yamlvalidatorGeneratedSchema"+prefix)
	formatted, err := format.Source([]byte(raw))
	if err != nil {
		return fmt.Errorf("format generated source: %w\n%s", err, raw)
	}
	if bytes.Equal(old, formatted) {
		return nil
	}
	if check {
		return fmt.Errorf("generated output is stale: %s", output)
	}
	return os.WriteFile(path, formatted, 0644)
}

func rejectConditionalTypes(pkg *packages.Package, names []string) error {
	selected := map[string]bool{}
	for _, name := range names {
		selected[name] = true
	}
	for i, file := range pkg.Syntax {
		if i >= len(pkg.CompiledGoFiles) {
			break
		}
		filename := filepath.Clean(pkg.CompiledGoFiles[i])
		if !sourceFileConditional(file, filename) {
			continue
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if ok && selected[ts.Name.Name] {
					return fmt.Errorf("type %s is build-constrained in %s; generate a file with matching constraints manually", ts.Name.Name, filepath.Base(filename))
				}
			}
		}
	}
	return nil
}

type root struct {
	name string
	id   int
}

type generator struct {
	pkg          *types.Package
	ids          map[string]int
	types        []types.Type
	bodies       []string
	roots        []root
	imports      map[string]string
	rootsByName  map[string]bool
	schemaFields map[int][]schemaField
}

func generatedStubs(old []byte, packageName string, selected []string) (string, error) {
	parsed, err := parser.ParseFile(token.NewFileSet(), "generated.go", old, 0)
	if err != nil {
		return "", fmt.Errorf("parse generated output: %w", err)
	}
	selectedSet := map[string]bool{}
	for _, name := range selected {
		selectedSet[name] = true
	}
	oldRoots := map[string]bool{}
	for _, decl := range parsed.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || fn.Name.Name != "YAMLValidatorGeneratedType" {
			continue
		}
		recv := fn.Recv.List[0].Type
		if star, ok := recv.(*ast.StarExpr); ok {
			recv = star.X
		}
		if name, ok := recv.(*ast.Ident); ok && selectedSet[name.Name] {
			oldRoots[name.Name] = true
		}
	}
	var b strings.Builder
	b.WriteString("package " + packageName + "\nimport (\"reflect\";yamlvalidator \"github.com/Yakwilik/go-yamlvalidator\";\"gopkg.in/yaml.v3\")\n")
	for _, name := range selected {
		if !oldRoots[name] {
			continue
		}
		fmt.Fprintf(&b, "func (value %s) YAMLValidatorGeneratedType() reflect.Type{return nil}\nfunc (value %s) YAMLValidatorCheckCycles(yamlvalidator.Limits)error{return nil}\nfunc (value %s) YAMLValidatorSchema(*yamlvalidator.Registry,bool)(*yamlvalidator.FieldSchema,error){return nil,nil}\nfunc (value %s) YAMLValidatorEncode()(*yaml.Node,error){return nil,nil}\nfunc (value *%s) YAMLValidatorDecode(*yaml.Node)error{return nil}\nfunc (value *%s) YAMLValidatorDecodeWithContext(*yaml.Node,*yamlvalidator.GeneratedDecodeContext)error{return nil}\nfunc (value %s) MarshalYAML()(any,error){return nil,nil}\nfunc (value *%s) UnmarshalYAML(*yaml.Node)error{return nil}\n", name, name, name, name, name, name, name, name)
	}
	if len(oldRoots) == 0 {
		return "package " + packageName + "\n", nil
	}
	return b.String(), nil
}

func (g *generator) typeText(t types.Type) string {
	return types.TypeString(t, func(p *types.Package) string {
		if p == g.pkg {
			return ""
		}
		if p.Path() == "github.com/Yakwilik/go-yamlvalidator" {
			return "yamlvalidator"
		}
		if p.Path() == "gopkg.in/yaml.v3" {
			return "yaml"
		}
		if alias, ok := g.imports[p.Path()]; ok {
			return alias
		}
		alias := fmt.Sprintf("dep%d", len(g.imports))
		g.imports[p.Path()] = alias
		return alias
	})
}

func (g *generator) ensure(t types.Type) (int, error) {
	key := types.TypeString(t, func(p *types.Package) string { return p.Path() })
	if id, ok := g.ids[key]; ok {
		return id, nil
	}
	id := len(g.ids)
	g.ids[key] = id
	g.types = append(g.types, t)
	// Reserve the body slot before visiting children so IDs and output order agree.
	g.bodies = append(g.bodies, "")
	body, err := g.makeBody(t, id)
	if err != nil {
		return 0, err
	}
	g.bodies[id] = body
	return id, nil
}

func (g *generator) makeBody(t types.Type, id int) (string, error) {
	typeName := g.typeText(t)
	var b strings.Builder
	fmt.Fprintf(&b, "func yamlvalidatorEncode%d(value %s) (*yaml.Node,error) {\n", id, typeName)
	base := types.Unalias(t)
	if named, ok := base.(*types.Named); ok {
		base = named.Underlying()
	}
	if customCodec(t) && !g.rootOrPointerType(t) {
		b.WriteString("return yamlvalidator.GeneratedFallbackEncode(value)\n}\n")
		fmt.Fprintf(&b, "func yamlvalidatorDecode%d(node *yaml.Node,dst *%s,ctx *yamlvalidator.GeneratedDecodeContext) error {if err:=ctx.Enter();err!=nil{return err};defer ctx.Leave();return yamlvalidator.GeneratedFallbackDecodeWithContext(node,dst,ctx) }\n", id, typeName)
		return b.String(), nil
	}
	switch u := base.(type) {
	case *types.Basic:
		under := g.typeText(u)
		if typeName == under {
			b.WriteString("return yamlvalidator.GeneratedScalarEncode(value)\n}\n")
		} else {
			fmt.Fprintf(&b, "return yamlvalidator.GeneratedScalarEncode(%s(value))\n}\n", under)
		}
		if typeName == under {
			fmt.Fprintf(&b, "func yamlvalidatorDecode%d(node *yaml.Node,dst *%s,ctx *yamlvalidator.GeneratedDecodeContext) error {if err:=ctx.Enter();err!=nil{return err};defer ctx.Leave();return yamlvalidator.GeneratedScalarDecode(node,dst)}\n", id, typeName)
		} else {
			fmt.Fprintf(&b, "func yamlvalidatorDecode%d(node *yaml.Node,dst *%s,ctx *yamlvalidator.GeneratedDecodeContext) error {if err:=ctx.Enter();err!=nil{return err};defer ctx.Leave();scalar:=%s(*dst); if err:=yamlvalidator.GeneratedScalarDecode(node,&scalar);err!=nil{return err}; *dst=%s(scalar);return nil }\n", id, typeName, under, typeName)
		}
		return b.String(), nil
	case *types.Pointer:
		child, err := g.ensure(u.Elem())
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "if value==nil{return yamlvalidator.GeneratedScalarEncode[any](nil)};return yamlvalidatorEncode%d(*value)\n}\n", child)
		fmt.Fprintf(&b, "func yamlvalidatorDecode%d(node *yaml.Node,dst *%s,ctx *yamlvalidator.GeneratedDecodeContext) error {if err:=ctx.Enter();err!=nil{return err};defer ctx.Leave();var err error;node,err=ctx.Resolve(node);if err!=nil{return err};if node.Tag==\"!!null\" {*dst=nil;return nil};if *dst==nil {*dst=new(%s)};return yamlvalidatorDecode%d(node,*dst,ctx) }\n", id, typeName, g.typeText(u.Elem()), child)
		return b.String(), nil
	case *types.Slice:
		if basic, ok := types.Unalias(u.Elem()).(*types.Basic); ok && basic.Kind() == types.Byte {
			return g.fallbackBody(t, id)
		}
		return g.sequenceBody(t, id, u.Elem(), -1)
	case *types.Array:
		return g.sequenceBody(t, id, u.Elem(), int(u.Len()))
	case *types.Map:
		keyBasic, ok := types.Unalias(u.Key()).Underlying().(*types.Basic)
		if !ok || keyBasic.Kind() != types.String {
			return "", fmt.Errorf("map key must be string or named string: %s", typeName)
		}
		child, err := g.ensure(u.Elem())
		if err != nil {
			return "", err
		}
		b.WriteString("node:=&yaml.Node{Kind:yaml.MappingNode,Tag:\"!!map\"}\n")
		fmt.Fprintf(&b, "keys:=make([]%s,0,len(value));for key:=range value {keys=append(keys,key)};sort.Slice(keys,func(i,j int)bool{return keys[i]<keys[j]});for _,key:=range keys { child,err:=yamlvalidatorEncode%d(value[key]);if err!=nil{return nil,err};node.Content=append(node.Content,&yaml.Node{Kind:yaml.ScalarNode,Tag:\"!!str\",Value:string(key)},child) };return node,nil\n}\n", g.typeText(u.Key()), child)
		fmt.Fprintf(&b, "func yamlvalidatorDecode%d(node *yaml.Node,dst *%s,ctx *yamlvalidator.GeneratedDecodeContext) error {if err:=ctx.Enter();err!=nil{return err};defer ctx.Leave();var err error;node,err=ctx.Resolve(node);if err!=nil{return err};if node.Tag==\"!!null\" {*dst=nil;return nil};pairs,err:=ctx.MappingPairs(node);if err!=nil{return err};if *dst==nil {*dst=make(%s,len(pairs))};for _,pair:=range pairs {var item %s;if err:=yamlvalidatorDecode%d(pair.Value,&item,ctx);err!=nil{return fmt.Errorf(\"key %%q: %%w\",pair.Key,err)};(*dst)[%s(pair.Key)]=item};return nil }\n", id, typeName, typeName, g.typeText(u.Elem()), child, g.typeText(u.Key()))
		return b.String(), nil
	case *types.Struct:
		return g.structBody(t, id, u)
	case *types.Interface:
		if u.NumMethods() != 0 {
			return "", fmt.Errorf("nonempty interface %s requires a type binding", typeName)
		}
		return g.fallbackBody(t, id)
	default:
		return "", fmt.Errorf("unsupported type %s", typeName)
	}
}

func (g *generator) rootType(t types.Type) bool {
	named, ok := types.Unalias(t).(*types.Named)
	return ok && named.Obj().Pkg() == g.pkg && g.rootsByName[named.Obj().Name()]
}

func (g *generator) rootOrPointerType(t types.Type) bool {
	for {
		if g.rootType(t) {
			return true
		}
		pointer, ok := types.Unalias(t).(*types.Pointer)
		if !ok {
			return false
		}
		t = pointer.Elem()
	}
}

func customCodec(t types.Type) bool {
	for _, typ := range []types.Type{t, types.NewPointer(t)} {
		m := types.NewMethodSet(typ)
		for i := 0; i < m.Len(); i++ {
			switch m.At(i).Obj().Name() {
			case "MarshalYAML", "UnmarshalYAML", "MarshalText", "UnmarshalText":
				return true
			}
		}
	}
	return false
}

func (g *generator) fallbackBody(t types.Type, id int) (string, error) {
	typeName := g.typeText(t)
	return fmt.Sprintf("func yamlvalidatorEncode%d(value %s) (*yaml.Node,error) { return yamlvalidator.GeneratedFallbackEncode(value) }\nfunc yamlvalidatorDecode%d(node *yaml.Node,dst *%s,ctx *yamlvalidator.GeneratedDecodeContext) error {if err:=ctx.Enter();err!=nil{return err};defer ctx.Leave();return yamlvalidator.GeneratedFallbackDecodeWithContext(node,dst,ctx)}\n", id, typeName, id, typeName), nil
}

func (g *generator) sequenceBody(t types.Type, id int, elem types.Type, length int) (string, error) {
	child, err := g.ensure(elem)
	if err != nil {
		return "", err
	}
	typeName := g.typeText(t)
	var b strings.Builder
	fmt.Fprintf(&b, "func yamlvalidatorEncode%d(value %s)(*yaml.Node,error){", id, typeName)
	fmt.Fprintf(&b, "node:=&yaml.Node{Kind:yaml.SequenceNode,Tag:\"!!seq\"};for _,item:=range value {child,err:=yamlvalidatorEncode%d(item);if err!=nil{return nil,err};node.Content=append(node.Content,child)};return node,nil}\n", child)
	fmt.Fprintf(&b, "func yamlvalidatorDecode%d(node *yaml.Node,dst *%s,ctx *yamlvalidator.GeneratedDecodeContext)error{if err:=ctx.Enter();err!=nil{return err};defer ctx.Leave();var err error;node,err=ctx.Resolve(node);if err!=nil{return err};", id, typeName)
	if length < 0 {
		b.WriteString("if node.Tag==\"!!null\" {*dst=nil;return nil};")
	}
	b.WriteString("if node.Kind!=yaml.SequenceNode{return fmt.Errorf(\"expected YAML sequence\")};")
	if length >= 0 {
		fmt.Fprintf(&b, "if len(node.Content)!=%d{return fmt.Errorf(\"expected %d sequence items\")};var result %s;", length, length, typeName)
	} else {
		fmt.Fprintf(&b, "result:=make(%s,len(node.Content));", typeName)
	}
	fmt.Fprintf(&b, "for i,item:=range node.Content {if err:=yamlvalidatorDecode%d(item,&result[i],ctx);err!=nil{return fmt.Errorf(\"item %%d: %%w\",i,err)}};*dst=result;return nil}\n", child)
	return b.String(), nil
}

type field struct {
	name, key          string
	id                 int
	omit, flow, inline bool
	pointer            bool
	mapInline          bool
	typ                types.Type
}

func sourceYAMLKeys(t types.Type, visiting map[types.Type]bool) []string {
	t = types.Unalias(t)
	if visiting[t] {
		return nil
	}
	visiting[t] = true
	defer delete(visiting, t)
	for {
		if p, ok := t.(*types.Pointer); ok {
			t = types.Unalias(p.Elem())
			continue
		}
		if n, ok := t.(*types.Named); ok {
			t = n.Underlying()
			continue
		}
		break
	}
	u, ok := t.(*types.Struct)
	if !ok {
		return nil
	}
	var out []string
	for i := 0; i < u.NumFields(); i++ {
		f := u.Field(i)
		if !f.Exported() {
			continue
		}
		parts := strings.Split(reflect.StructTag(u.Tag(i)).Get("yaml"), ",")
		if parts[0] == "-" {
			continue
		}
		inline := false
		for _, flag := range parts[1:] {
			if flag == "inline" {
				inline = true
			}
		}
		if inline {
			out = append(out, sourceYAMLKeys(f.Type(), visiting)...)
			continue
		}
		name := parts[0]
		if name == "" {
			name = strings.ToLower(f.Name())
		}
		out = append(out, name)
	}
	return out
}

func (g *generator) structBody(t types.Type, id int, u *types.Struct) (string, error) {
	typeName := g.typeText(t)
	fields := []field{}
	keys := map[string]bool{}
	var parentGroups []taglang.Rule
	for i := 0; i < u.NumFields(); i++ {
		f := u.Field(i)
		if _, err := taglang.ParseStructTag(u.Tag(i)); err != nil {
			return "", fmt.Errorf("field %s: %w", f.Name(), err)
		}
		tag := reflect.StructTag(u.Tag(i))
		if _, ok := tag.Lookup("yamljsonschema"); ok {
			return "", fmt.Errorf("field %s: yamljsonschema is unsupported", f.Name())
		}
		validation, hasValidation := tag.Lookup("yamlvalidate")
		if hasValidation {
			rules, err := taglang.Parse(validation)
			if err != nil {
				return "", fmt.Errorf("field %s: %w", f.Name(), err)
			}
			_, parent, normalErr := taglang.Normalize(rules, taglang.FieldScope)
			if normalErr != nil {
				err = normalErr
				return "", fmt.Errorf("field %s: %w", f.Name(), err)
			}
			parentGroups = append(parentGroups, parent...)
			for _, rule := range rules {
				if !sourceRuleKnown(rule.Key) {
					return "", fmt.Errorf("field %s: unknown validation directive %q at byte %d", f.Name(), rule.Key, rule.Offset)
				}
			}
			if err := checkSourceBounds(rules); err != nil {
				return "", fmt.Errorf("field %s: %w", f.Name(), err)
			}
		}
		if !f.Exported() {
			if hasValidation {
				return "", fmt.Errorf("field %s: validation tag on unexported field", f.Name())
			}
			continue
		}
		parts := strings.Split(tag.Get("yaml"), ",")
		name := parts[0]
		if name == "-" {
			if hasValidation {
				return "", fmt.Errorf("field %s: validation tag on excluded field", f.Name())
			}
			continue
		}
		if name == "" {
			name = strings.ToLower(f.Name())
		}
		item := field{name: f.Name(), key: name, typ: f.Type()}
		for _, flag := range parts[1:] {
			switch flag {
			case "omitempty":
				item.omit = true
			case "flow":
				item.flow = true
			case "inline":
				item.inline = true
			default:
				return "", fmt.Errorf("field %s: unsupported yaml flag %q", f.Name(), flag)
			}
		}
		if item.inline && parts[0] != "" {
			return "", fmt.Errorf("field %s: inline cannot have a YAML name", f.Name())
		}
		if !item.inline {
			if keys[name] {
				return "", fmt.Errorf("duplicate YAML key %q", name)
			}
			keys[name] = true
		}
		if p, ok := types.Unalias(f.Type()).(*types.Pointer); ok {
			item.pointer = true
			_ = p
		}
		if item.inline {
			base := types.Unalias(f.Type())
			for {
				p, ok := base.(*types.Pointer)
				if !ok {
					break
				}
				base = types.Unalias(p.Elem())
			}
			if named, ok := base.(*types.Named); ok {
				base = named.Underlying()
			}
			_, item.mapInline = base.(*types.Map)
		}
		child, err := g.ensure(f.Type())
		if err != nil {
			return "", fmt.Errorf("field %s: %w", f.Name(), err)
		}
		item.id = child
		fields = append(fields, item)
		g.schemaFields[id] = append(g.schemaFields[id], schemaField{field: item, tag: validation})
	}
	allKeys := map[string]bool{}
	for _, field := range fields {
		if field.inline {
			for _, key := range sourceYAMLKeys(field.typ, map[types.Type]bool{}) {
				allKeys[key] = true
			}
		} else {
			allKeys[field.key] = true
		}
	}
	for _, rule := range parentGroups {
		switch rule.Key {
		case "exactlyOneOf", "require", "mutuallyExclusive":
			if rule.Value.Kind != taglang.List {
				continue
			}
			for _, member := range rule.Value.List {
				if !allKeys[member.Text] {
					return "", fmt.Errorf("%s: unknown YAML field %q", rule.Key, member.Text)
				}
			}
		}
	}
	var b strings.Builder
	var fingerprint strings.Builder
	fingerprint.WriteString(typeName)
	for i := 0; i < u.NumFields(); i++ {
		fmt.Fprintf(&fingerprint, "|%s|%s|%q", u.Field(i).Name(), g.typeText(u.Field(i).Type()), u.Tag(i))
	}
	digest := sha256.Sum256([]byte(fingerprint.String()))
	fmt.Fprintf(&b, "// yamlvalidator source fingerprint: %x\n", digest[:12])
	fmt.Fprintf(&b, "func yamlvalidatorEncode%d(value %s)(*yaml.Node,error){node:=&yaml.Node{Kind:yaml.MappingNode,Tag:\"!!map\"};", id, typeName)
	if len(fields) > 0 {
		b.WriteString("var child *yaml.Node;var err error;")
	}
	b.WriteByte('\n')
	for _, f := range fields {
		if f.omit {
			fmt.Fprintf(&b, "if !yamlvalidatorEmpty%d(value.%s) {\n", f.id, f.name)
		}
		fmt.Fprintf(&b, "child,err=yamlvalidatorEncode%d(value.%s);if err!=nil{return nil,fmt.Errorf(\"field %s: %%w\",err)};", f.id, f.name, f.name)
		if f.flow {
			b.WriteString("child.Style|=yaml.FlowStyle;")
		}
		if f.inline {
			b.WriteString("if err:=yamlvalidator.GeneratedAppendInline(node,child);err!=nil{return nil,err};")
		} else {
			fmt.Fprintf(&b, "node.Content=append(node.Content,&yaml.Node{Kind:yaml.ScalarNode,Tag:\"!!str\",Value:%q},child);", f.key)
		}
		if f.omit {
			b.WriteString("}\n")
		}
	}
	b.WriteString("return node,nil}\n")
	fmt.Fprintf(&b, "func yamlvalidatorDecode%d(node *yaml.Node,dst *%s,ctx *yamlvalidator.GeneratedDecodeContext)error{if err:=ctx.Enter();err!=nil{return err};defer ctx.Leave();pairs,err:=ctx.MappingPairs(node);if err!=nil{return err};for _,pair:=range pairs {switch pair.Key {\n", id, typeName)
	for _, f := range fields {
		if !f.inline {
			fmt.Fprintf(&b, "case %q:if err:=yamlvalidatorDecode%d(pair.Value,&dst.%s,ctx);err!=nil{return fmt.Errorf(\"field %s: %%w\",err)}\n", f.key, f.id, f.name, f.name)
		}
	}
	b.WriteString("}}\n")
	for _, f := range fields {
		if !f.inline {
			continue
		}
		if f.mapInline {
			b.WriteString("{inlineNode:=&yaml.Node{Kind:yaml.MappingNode,Tag:\"!!map\"};for _,pair:=range pairs{switch pair.Key{")
			known := map[string]bool{}
			for _, other := range fields {
				if !other.inline {
					known[other.key] = true
				} else if !other.mapInline {
					for _, key := range sourceYAMLKeys(other.typ, map[types.Type]bool{}) {
						known[key] = true
					}
				}
			}
			knownKeys := make([]string, 0, len(known))
			for key := range known {
				knownKeys = append(knownKeys, key)
			}
			sort.Strings(knownKeys)
			for _, key := range knownKeys {
				fmt.Fprintf(&b, "case %q:\n", key)
			}
			b.WriteString("default:inlineNode.Content=append(inlineNode.Content,&yaml.Node{Kind:yaml.ScalarNode,Tag:\"!!str\",Value:pair.Key},pair.Value)}};")
			fmt.Fprintf(&b, "if err:=yamlvalidatorDecode%d(inlineNode,&dst.%s,ctx);err!=nil{return fmt.Errorf(\"field %s: %%w\",err)}};", f.id, f.name, f.name)
		} else {
			fmt.Fprintf(&b, "if err:=yamlvalidatorDecode%d(node,&dst.%s,ctx);err!=nil{return fmt.Errorf(\"field %s: %%w\",err)};", f.id, f.name, f.name)
		}
	}
	b.WriteString("return nil}\n")
	return b.String(), nil
}

func checkSourceBounds(rules []taglang.Rule) error {
	values := map[string]*big.Rat{}
	for _, rule := range rules {
		switch rule.Key {
		case "min", "max", "minLength", "maxLength", "minItems", "maxItems", "minProperties", "maxProperties":
			if rule.Value.Kind != taglang.Atom && rule.Value.Kind != taglang.String {
				continue
			}
			v, ok := new(big.Rat).SetString(rule.Value.Text)
			if ok {
				values[rule.Key] = v
			}
		}
	}
	for _, pair := range [][2]string{{"min", "max"}, {"minLength", "maxLength"}, {"minItems", "maxItems"}, {"minProperties", "maxProperties"}} {
		lo, hasLo := values[pair[0]]
		hi, hasHi := values[pair[1]]
		if hasLo && hasHi && lo.Cmp(hi) > 0 {
			return fmt.Errorf("%s exceeds %s", pair[0], pair[1])
		}
	}
	return nil
}

func sourceRuleKnown(name string) bool {
	switch name {
	case "required", "nullable", "notnull", "nonempty", "uniqueItems", "type", "types", "deprecated", "description", "default", "minItems", "maxItems", "items", "properties", "additional", "unknown", "values", "keys", "min", "max", "minLength", "maxLength", "minProperties", "maxProperties", "enum", "pattern", "url", "format", "check", "checks", "ref", "oneOfSchemas", "anyOfSchemas", "require", "anyOfRequired", "exactlyOneOf", "mutuallyExclusive", "oneOfRequired", "forbiddenTogether", "dependentRequired", "when", "requireKeys", "anyOfRequiredKeys", "exactlyOneOfKeys", "mutuallyExclusiveKeys", "oneOfRequiredKeys", "forbiddenTogetherKeys", "dependentRequiredKeys", "whenKeys":
		return true
	}
	return false
}
