package main

import (
	"bytes"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateAndRun(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	root := filepath.Dir(filepath.Dir(wd))
	dir := t.TempDir()
	write := func(name, content string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0600); err != nil {
			t.Fatal(err)
		}
	}
	write("go.mod", "module fixture\n\ngo 1.24.0\n\nrequire (\ngithub.com/Yakwilik/go-yamlvalidator v0.0.0\ngopkg.in/yaml.v3 v3.0.1\n)\nreplace github.com/Yakwilik/go-yamlvalidator => "+root+"\n")
	write("types.go", `package fixture
import api "github.com/Yakwilik/go-yamlvalidator"
type NativeKind struct { Kind api.NodeType }
type Child struct { Name string `+"`yaml:\"name\" yamlvalidate:\"required,minLength=2\"`"+` }
type Config struct {
  Child Child `+"`yaml:\"child\"`"+`
  Items []Child `+"`yaml:\"items\"`"+`
  Counts map[string]int `+"`yaml:\"counts\"`"+`
}
type Parent struct { Child Child `+"`yaml:\"child\"`"+` }
type PointerOnly struct { Value string }
func (p *PointerOnly) MarshalYAML() (any,error) {return "custom-"+p.Value,nil}
type MixedCustom struct {Child Child `+"`yaml:\"child\"`"+`; Custom *PointerOnly `+"`yaml:\"custom\"`"+`}
type InlineConfig struct {
 Child Child `+"`yaml:\"child\"`"+`
 Extra map[string]int `+"`yaml:\",inline\"`"+`
}
type Empty struct{}
`)
	write("types_test.go", `package fixture
import (
 "testing"
 "strings"
 v "github.com/Yakwilik/go-yamlvalidator"
 "gopkg.in/yaml.v3"
)
func TestCodec(t *testing.T) {
 var c Config
 data := []byte("child: {name: ok}\nitems: [{name: yes}]\ncounts: {x: 2}\n")
 if err := v.Unmarshal(data, &c); err != nil { t.Fatal(err) }
 if c.Child.Name != "ok" || c.Items[0].Name != "yes" || c.Counts["x"] != 2 { t.Fatalf("%+v", c) }
 if err := yaml.Unmarshal([]byte("child: {name: x}\n"), &c); err == nil { t.Fatal("standard hook did not validate") }
 b, err := v.Marshal(c); if err != nil { t.Fatal(err) }; if len(b)==0 { t.Fatal("empty") }
 var parent Parent
 if err:= (v.UnmarshalOptions{UnknownKeyPolicy:v.UnknownKeyIgnore}).Unmarshal([]byte("child: {name: ok, extra: yes}\n"),&parent);err!=nil {t.Fatal(err)}
 if parent.Child.Name!="ok" {t.Fatalf("%+v",parent)}
 if _,err:=(v.MarshalOptions{SkipValidation:true}).Marshal(Parent{Child:Child{Name:"x"}});err!=nil {t.Fatal(err)}
 customBytes,err:=(v.MarshalOptions{SkipValidation:true}).Marshal(MixedCustom{Child:Child{Name:"ok"},Custom:&PointerOnly{Value:"yes"}})
 if err!=nil || !strings.Contains(string(customBytes),"custom-yes") {t.Fatalf("custom: %s %v",customBytes,err)}
 var inline InlineConfig
 if err:=v.Unmarshal([]byte("child: {name: ok}\nextra: 3\n"),&inline);err!=nil {t.Fatal(err)}
 if len(inline.Extra)!=1 || inline.Extra["extra"]!=3 {t.Fatalf("inline: %+v",inline)}
 if _,err:=(v.MarshalOptions{SkipValidation:true}).Marshal(InlineConfig{Child:Child{Name:"ok"},Extra:map[string]int{"child":1}});err==nil {t.Fatal("inline collision accepted")}
}
`)
	cmd := exec.Command("go", "run", "github.com/Yakwilik/go-yamlvalidator/cmd/yamlvalidator-gen", "-type=Child,Config,InlineConfig,NativeKind", "-output=zz_generated.go")
	cmd.Dir = dir
	// Inherit GOPROXY: fresh CI caches may need transitive module metadata.
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generator: %v\n%s", err, out)
	}
	write("use.go", "package fixture\nimport \"gopkg.in/yaml.v3\"\nvar _ yaml.Marshaler = Config{}\n")
	cmd = exec.Command("go", "test", "-mod=mod", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("fixture: %v\n%s", err, out)
	}
	cmd = exec.Command("go", "run", "github.com/Yakwilik/go-yamlvalidator/cmd/yamlvalidator-gen", "-type=Child,Config,InlineConfig,NativeKind", "-output=zz_generated.go", "-check")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("check: %v\n%s", err, out)
	}
	generated, err := os.ReadFile(filepath.Join(dir, "zz_generated.go"))
	if err != nil {
		t.Fatal(err)
	}
	formatted, formatErr := format.Source(generated)
	if formatErr != nil || !bytes.Equal(generated, formatted) {
		t.Fatalf("generated output is not gofmt-stable: %v", formatErr)
	}
	if !strings.Contains(string(generated), "Code generated by yamlvalidator-gen") {
		t.Fatal("missing marker")
	}
	for _, forbidden := range []string{
		"SourceTypePlan", "reflect.StructField", "GeneratedRule", "GeneratedRuleValue",
		"github.com/Yakwilik/go-yamlvalidator/internal/",
		"normalizeFieldRules", "applyRules", "compileHighLevel",
		"yamlvalidator.GeneratedScalar", "yamlvalidator.GeneratedFallback",
		"yamlvalidator.GeneratedAppendInline", "yamlvalidator.GeneratedIsEmpty",
		"yamlvalidator.GeneratedDecodeContext", "yamlvalidator.GeneratedCycleContext",
		"MarshalGenerated", "UnmarshalGenerated", "BuildGeneratedSchema", "LowerGeneratedSchema",
	} {
		if strings.Contains(string(generated), forbidden) {
			t.Fatalf("generated source contains runtime schema-lowering metadata %q", forbidden)
		}
	}
	if !strings.Contains(string(generated), "YAMLValidatorSchemaSpec") || !strings.Contains(string(generated), "Required:") {
		t.Fatal("generated source is missing the normalized schema")
	}
	if !strings.Contains(string(generated), "genruntime.") || !strings.Contains(string(generated), "spec.Graph") {
		t.Fatal("generated source is not using the dedicated generated runtime ABI")
	}
	cmd = exec.Command("go", "run", "github.com/Yakwilik/go-yamlvalidator/cmd/yamlvalidator-gen", "-type=Empty", "-output=zz_empty.go")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("second output: %v\n%s", err, out)
	}
	cmd = exec.Command("go", "test", "-mod=mod", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("two outputs: %v\n%s", err, out)
	}
	write("owned.go", "package fixture\n")
	cmd = exec.Command("go", "run", "github.com/Yakwilik/go-yamlvalidator/cmd/yamlvalidator-gen", "-type=Empty", "-output=owned.go")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if out, err := cmd.CombinedOutput(); err == nil || !strings.Contains(string(out), "user-owned") {
		t.Fatalf("ownership: %v\n%s", err, out)
	}
	write("hidden.go", "//go:build never\n\npackage fixture\ntype Hidden struct{}\n")
	cmd = exec.Command("go", "run", "github.com/Yakwilik/go-yamlvalidator/cmd/yamlvalidator-gen", "-type=Hidden", "-output=zz_hidden.go")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if out, err := cmd.CombinedOutput(); err == nil || !strings.Contains(string(out), "Hidden") {
		t.Fatalf("build constraint: %v\n%s", err, out)
	}
	source, err := os.ReadFile(filepath.Join(dir, "types.go"))
	if err != nil {
		t.Fatal(err)
	}
	changed := strings.Replace(string(source), "type Config struct {\n", "type Config struct {\n Added string\n", 1)
	write("types.go", changed)
	cmd = exec.Command("go", "run", "github.com/Yakwilik/go-yamlvalidator/cmd/yamlvalidator-gen", "-type=Child,Config,InlineConfig,NativeKind", "-output=zz_generated.go", "-check")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if out, err := cmd.CombinedOutput(); err == nil || !strings.Contains(string(out), "stale") {
		t.Fatalf("stale check: %v\n%s", err, out)
	}
	still, err := os.ReadFile(filepath.Join(dir, "zz_generated.go"))
	if err != nil {
		t.Fatal(err)
	}
	if string(still) != string(generated) {
		t.Fatal("check changed output")
	}
	cmd = exec.Command("go", "run", "github.com/Yakwilik/go-yamlvalidator/cmd/yamlvalidator-gen", "-type=Child,Config,InlineConfig,NativeKind", "-output=zz_generated.go")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("regenerate: %v\n%s", err, out)
	}
	tagChanged := strings.Replace(changed, "minLength=2", "minLength=3", 1)
	write("types.go", tagChanged)
	cmd = exec.Command("go", "run", "github.com/Yakwilik/go-yamlvalidator/cmd/yamlvalidator-gen", "-type=Child,Config,InlineConfig,NativeKind", "-output=zz_generated.go", "-check")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if out, err := cmd.CombinedOutput(); err == nil || !strings.Contains(string(out), "stale") {
		t.Fatalf("tag staleness: %v\n%s", err, out)
	}
	write("types.go", changed+"\nfunc (Config) MarshalYAML() (any,error) {return nil,nil}\n")
	cmd = exec.Command("go", "run", "github.com/Yakwilik/go-yamlvalidator/cmd/yamlvalidator-gen", "-type=Child,Config,InlineConfig,NativeKind", "-output=zz_generated.go")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if out, err := cmd.CombinedOutput(); err == nil || !strings.Contains(string(out), "MarshalYAML already declared") {
		t.Fatalf("method collision: %v\n%s", err, out)
	}
}
